name: food_recognizer_client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  go_router: ^16.2.4
  flutter_displaymode: ^0.7.0
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  camera: ^0.11.2+1
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# ←←← ВАЖНО: flutter_launcher_icons НЕ внутри flutter и НЕ внутри dev_dependencies!
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  # assets можно добавить, если нужно:
  # assets:
  #   - assets/icon/app_icon.png